### ISSUE TITLE
Unmaintained? 

### ISSUE THREAD

**Issue by ivobenedito** [opensourcerails/opensourcerails#143]
What happened to this project? :(

The last commit is from more than 1 year ago and there are so many open issues referring other Open Source projects to be appended to the list but they never get added.

**Comment by mbajur** [comment]
I'm running my own attempt at reddit: https://www.reddit.com/r/rubyapps (not just rails but ruby as a whole) but such effort demands a separate website for sure.

As few people (including me) mentioned in here before - opensourcerails generates an impression that ruby/rails community is dying which is probably a opposite of what it aimed to achieve

**Comment by ivobenedito** [comment]
@mbajur Unfortunately what you're saying is the truth. The project itself is not passing the right message to the community.
The **reddit** alternative is pretty nice, but having an updated website for opensourcerails would always be better. 

Could a fork of this project make sense?

**Comment by railsjedi** [comment]
No need to fork the project. Anyone who wants to become a maintainer, I'm happy to give them admin access

Also.. sorry! I didn't mean for this project to go down the toilet again, but it keeps happening :(

**Comment by mbajur** [comment]
No worries railsjedi! We just need to figure something out :)

I could help in some way but i'm just not the biggest fan of restricting it to rails only projects. There are plenty of apps not written in rails that are still worth mentioning but built using ruby - like for example `barkeep` issue added here recently and closed after a while because it's made with sinatra. 

In the times when rails were the #1 hip framework to create a web apps it maked sense so i totally understand your decision. But things changed and **personally** i think it would be much more beneficial for ruby/rails community (and for people thinking about learning ruby [on rails]) to promote **any** app and tool written in ruby rather than restricting ourselves to rails apps

Anyway i'm writing that comment in `opensourceRAILS` project so it probably doesn't make sense haha

**Comment by railsjedi** [comment]
@mbajur cool, i don't have any restriction for opensourcerails. all ruby web apps apply

precedence: rails rumble also accepts all ruby apps (not just rails). rails is just good branding is all :)

**Comment by mbajur** [comment]
Oh, sorry, i always thought that opensourcerails is only about rails projects (btw - isn't that a small sign that the `rails` word in ruby ecosystem is a bit misleading? i have also seen that i'm not the only one with such problem)

that's not a name change suggestion - i'm just thinking out loud :)

**Comment by railsjedi** [comment]
no prob. yeah, it's hard to come up with a better name. opensourceruby would be misleading because i do want to limit the gallery to open source web apps. opensourcerails is good shorthand for that.

alternatives would get wonky. opensourcerubywebapps.com opensourcerubyweb

anyways, in the meantime i'd be ok changing the copy on the site to "open source rails (or alternative frameworks)"

**Comment by railsjedi** [comment]
An ideas for getting this dead site back moving again:

1) Move repo to a github organization, add all volunteers with write access

2) Create a Slack channel that volunteers will get access to

3) Curate and post a new project every week

4) create some development tickets to fix the scalability issue (needs pagination / search, or some other things)

5) get heroku or something to sponsor hosting so its a bit easier than my hacking static site deploy process

**Comment by ivobenedito** [comment]
@railsjedi I'm all in. I'll help in all I can.

**Comment by mbajur** [comment]
What about rubyapps (skip opensource word from name but keep it everywhere else) - just like my subreddit? The only difference is that i'm also listing closed-source apps because i believe it's also a cool source of information when it comes to check what's going on with the ruby community and if anyone is using it at all (for newcommers). It's good to know for anyone that there are any big shots using ruby. Like, for example, github. It's just *healthy* to publish such list somewhere.

I'm also keen to help! Anyway - isn't that better idea to use gitter instead of slack for such "open" project? I suppose that chat is mainly aimed to be maintained by developers and i'm pretty sure that almost all [ruby] developers has a github account (which is needed for gitter). Slack is great but not everyone are using it so that will probably lower an amount of people keen to use it to chat with us

**Comment by railsjedi** [comment]
+1 on gitter. I might also set up a slack for the volunteer group, because then I can have it open all the time and respond to things quicker, but gitter makes a ton of sense as a general public chatroom

I'll get everything set up tomorrow and add you guys as admins on the github rep. Thanks!!

**Comment by ivobenedito** [comment]
cool :+1:

**Comment by railsjedi** [comment]
I've set up the new github organization, sent out maintainer invites, added gitter, and also set up a ![slack account](opensourcerails.slack.com)

**Comment by railsjedi** [comment]
email me at jcnetdev@gmail.com if you'd like to join the slack. we'll use it to plan which open source project gets posted next, and to discuss other dev activities (like deploys, bug fixes, etc)

**Comment by railsjedi** [comment]
next i'm working on moving hosting over to divshot.com (so i can add collaborators to deploy) and also make a few long needed tweaks to the template

**Comment by railsjedi** [comment]
also cleaned up the twitter account https://twitter.com/opensourcerails

**Comment by mario** [comment]
@railsjedi I have no problems sponsoring a hosting if you'd like.

**Comment by railsjedi** [comment]
@mario divshot seems like a good free solution until we go dynamic. i'll add all the maintainers as collabs on the divshot project so anyone can deploy whenever they want
